[pyprland]
plugins = [
    "scratchpads"
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"
unfocus = "hide"

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol -t 3"
class = "org.pulseaudio.pavucontrol"
lazy = true
size = "40% 90%"
unfocus = "hide"
close_on_hide = true
hide_delay = 0.2
