#!/bin/bash
text=$(cliphist list | tofi -c ~/.config/tofi/conf | cliphist decode)
if [ "$text" != "" ]; then
    echo "$text" | wl-copy
    active_window=$(hyprctl -j activewindow)
    window_class=$(echo "$active_window" | jq -r '.class')
    ydotool key 29:1 47:1 47:0 29:0
    # if [ "$window_class" = "kitty" ]; then
    #     hyprctl dispatch sendshortcut "CTRL SHIFT, V,"
    # else
    #     hyprctl dispatch sendshortcut "CTRL, V,"
    # fi
fi
exit
