#!/bin/bash
text=$(cliphist list | tofi -c ~/.config/tofi/conf | cliphist decode | tee >(wl-copy))
if [ "$text" != "" ]; then
    active_window=$(hyprctl -j activewindow)
    window_title=$(echo "$active_window" | jq -r '.title')
    if [[ "$window_title" =~ ^v($| .*) ]]; then
        ydotool key 1:1 1:0 25:1 25:0
    else
        ydotool key 29:1 47:1 47:0 29:0
    fi
fi
exit
